name: teslo_shop
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  arkit_plugin: ^1.0.7
  dio: ^5.3.2
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_polyline_points: ^2.0.0
  flutter_riverpod: ^2.4.0
  flutter_staggered_grid_view: ^0.7.0
  formz: ^0.6.0
  go_router: ^6.2.0
  google_fonts: ^4.0.3
  google_maps_flutter: ^2.5.0
  location: ^5.0.3
  permission_handler: ^11.0.0
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  video_player: ^2.7.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env
    - assets/loaders/
    - assets/images/
    - google_fonts/montserrat_alternates/
